name = "mp3-converter"
compatibility_date = "2025-01-21"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true